apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-sentinel-config
  namespace: cloud-sentinel
data:
  AWS_ENDPOINT: "http://localstack:4566"
  AWS_REGION: "us-east-1"
  AWS_S3_BUCKET: "cloud-sentinel-docs"
  AWS_DYNAMODB_USERS_TABLE: "cloud-sentinel-users"
  AWS_DYNAMODB_AUDIT_TABLE: "cloud-sentinel-audit"
  SERVER_PORT: "8080"
  SPRING_PROFILES_ACTIVE: "k8s"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: localstack-config
  namespace: cloud-sentinel
data:
  SERVICES: "s3,dynamodb,iam,sts"
  DEFAULT_REGION: "us-east-1"
  EDGE_PORT: "4566"
