apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: cloud-sentinel
data:
  datasources.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
        editable: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards-config
  namespace: cloud-sentinel
data:
  dashboards.yml: |
    apiVersion: 1
    providers:
      - name: 'CloudSentinel'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards
          foldersFromFilesStructure: false
