apiVersion: v1
kind: Secret
metadata:
  name: cloud-sentinel-secrets
  namespace: cloud-sentinel
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "CHANGE_ME"
  AWS_SECRET_ACCESS_KEY: "CHANGE_ME"
  JWT_SECRET: "CHANGE_ME_BASE64_ENCODED_SECRET"
  DB_USERNAME: "cloudsentinel"
  DB_PASSWORD: "CHANGE_ME"
